[package]
name = "rocket-server"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.rocket]
version = "0.5.0"

[dependencies.rocket_db_pools]
version = "0.1.0"
features = ["sqlx_sqlite"]

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["tera"]
